name: Publish KAPE files

on:
  push:
    branches:
      - airt-kape-release
  
jobs:
  Publish-files:
    runs-on: windows-latest   # PowerShell runs better natively on Windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Release KAPE bundles to GH Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: KAPE-releases
          name: KAPE AteaIRT releases
          files: |
            ./KAPE_AteaIRT_LiveForensic.zip
            ./KAPE_AteaIRT_Collector.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
